### ISSUE TITLE
Redirects for marketing campaign

### ISSUE THREAD

**Issue by stephaniehobson** [mozmeao/www.firefox.com#13]
Requested redirects:

firefox.com/unfuck
firefox.com/unfck

Redirect to:

www.mozilla.org/firefox/unfck/

**Comment by pmac** [comment]
@duallain I have a PR open for this change for www.firefox.com, but do we also need to do it for firefox.com or is that going to just redirect to www.firefox.com?

**Comment by duallain** [comment]
looks like redirects are maintained:

```
$ curl www.firefox.com/desktop
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.17.10</center>
</body>
</html>

$ curl firefox.com/desktop
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.mozilla.org/firefox/desktop/?redirect_source=firefox-com">here</a>.</p>
</body></html>
```

So I think we should be good. (Probably good to test to be sure, but I don't see why the unfck paths would behave differently).

**Comment by pmac** [comment]
@duallain currently IT maintains the apex domain redirects and we (MEAO) maintain the www subdomain ones. They're not synced.

**Comment by pmac** [comment]
So I guess we also need to file an issue to have these directs added to IT's redirector service for firefox.com?

**Comment by duallain** [comment]
Ended up making the request here: https://jira.mozilla.com/browse/SE-1256  

@stephaniehobson are there any timing considerations to take into account? (Is there a too soon, and/or a too late?)

**Comment by pmac** [comment]
@duallain would it make sense to just have the fx.c redirector redirect all requests to www.fx.c so we can manage them all in one place?

**Comment by stephaniehobson** [comment]
@duallain Is Sept 18 reasonable?

**Comment by duallain** [comment]
> @duallain would it make sense to just have the fx.c redirector redirect all requests to [www.fx.c](http://www.fx.c) so we can manage them all in one place?

We could. Doesn't seem unreasonable to me.  Probably split the requests into two so we get the campaign setup well, and it can take however long it takes to do the full redirect work (with path/query preservation).  If you want to write the full feature out, that'd help a ton.  Mostly just, what does the www.firefox.com redirector need as inputs to work well?




> @duallain Is Sept 18 reasonable?

I think so.  Included that date in the story, will try to make it happen.  Will chat in team meeting tomorrow and see if there's any issues with the date.

**Comment by pmac** [comment]
> Mostly just, what does the [www.firefox.com](http://www.firefox.com) redirector need as inputs to work well?

I don't know what this means. I'm just suggesting that `https://firefox.com` redirect all requests, intact, to `https://www.firefox.com` using a 301.

**Comment by pmac** [comment]
Reopening for continuing discussion of the apex domain redirect

**Comment by duallain** [comment]
> > Mostly just, what does the [www.firefox.com](http://www.firefox.com) redirector need as inputs to work well?
> 
> I don't know what this means. I'm just suggesting that `https://firefox.com` redirect all requests, intact, to `https://www.firefox.com` using a 301.

Ahh.  I'm not 100% sure what fully intact implies in this context. (Which is what I'm trying to express with 'inputs'). I assume paths/headers are enough? Seems like we don't care about query params for this website. I've seen redirect services 'eat' some of that context and not forward it on, which can break downstream applications.  Trying to expand the requirements a bit so we don't get bit by an edge case.

It doesn't seem like an unreasonable request.  Probably not too much work.  Not sure what the priority for it would be, but could certainly go to jira at least.

**Comment by pmac** [comment]
I believe we do care about query params. What I mean by "intact" in this case is basically a replay of the request but at `www.fx.c` instead of `fx.c`. We don't really have control over headers for a redirect, the client's browser will handle that, but the full URL path and query params should be included in the redirect. In some cases the query params are forwarded to the final destination, and in others they are modified.

**Comment by pmac** [comment]
> It doesn't seem like an unreasonable request. Probably not too much work. Not sure what the priority for it would be, but could certainly go to jira at least.

Probably not a high priority, but it would mean we'd no longer need to ask IT for help with any of these redirects again, so maybe y'all will find it more of a priority for that reason that we do.

**Comment by pmac** [comment]
Although if you point me to where the other redirects are (I don't think refractr is in prod yet right?) then I'm happy to submit a PR for the change on that end as well.

**Comment by stephaniehobson** [comment]
We also need firefox.com/love. Should I create a new issue for that?

**Comment by pmac** [comment]
> We also need firefox.com/love. Should I create a new issue for that?

Yes please. The PR for the original ones here has already been merged.

**Comment by pmac** [comment]
We've decided that the apex domain redirector will send all traffic to www.fx.c so that the redirects in this repo are authoritative. Closing.
