### ISSUE TITLE
Redirect for marketing campaign

### ISSUE THREAD

**Issue by stephaniehobson** [mozmeao/www.firefox.com#15]
Requested redirect:

firefox.com/love

Redirect to:

www.mozilla.org/firefox/unfck/

**Comment by pmac** [comment]
@stephaniehobson I forgot to ask: any query params you need on the redirect? e.g. many of them use `?redirect_source=firefox-com` but some add more. The redirector will combine that with whatever params are on the incoming request as well.

**Comment by pmac** [comment]
I confirmed with @hoosteeno that it's a good idea to add the `?redirect_source=firefox-com` param to the campaign redirects. Any incoming query params will be combined with this one, and I added a test to ensure this is the case.
