### ISSUE TITLE
Include utm parameters in september campaign redirects

### ISSUE THREAD

**Issue by alexgibson** [mozmeao/www.firefox.com#19]
Currently https://firefox.com/unfck redirects to https://www.mozilla.org/en-US/firefox/?redirect_source=firefox-com

I've received some questions around stub attribution and understanding the install rate based on this specific campaign and its messaging. If that's something important to measure, then these redirects should include utm parameters so that we can attribute things correctly.

What those utm parameters should be needs to be decided on.

**Comment by pmac** [comment]
To be clear, if the link to the redirect via a campaign includes other query params they will be added to the `redirect_source` one that the redirector adds. So we can definitely add more, but I believe the thought is that we'd be adding those in the campaign links if they link to the redirector. If we won't be linking to www.firefox.com for this and instead linking directly to WMO then perhaps we should add some more. I believe even if we do add some and the same param comes in from a campaign link that the incoming value will override, but we'd have to test that.

**Comment by pmac** [comment]
Actually it's additive:

```shell
$ curl -I "https://www.firefox.com/unfck?redirect_source=the-dude" | grep location
location: https://www.mozilla.org/firefox/unfck/?redirect_source=firefox-com&redirect_source=the-dude
```

**Comment by alexgibson** [comment]
From a marketing perspective I believe we're using firefox.com/unfck in various places. Some of those places may be in tweets on twitter, in ads, on podcasts or in other forms. I'm assuming they may not necessarily include utm params

**Comment by stephaniehobson** [comment]
I've asked to social team what UTMs they will be adding to their link shorteners. If UTMs are the best way to handle this we can pattern ours after that.

**Comment by stephaniehobson** [comment]
For the most part we can expect that firefox.com/unfck will include UTMs.

These are the UTMs to be added for people coming to `firefox.com/unfck` or a misspelling - _if there are not already UTMs._ Is this possible, I can't tell from reading the above? @pmac please let me know if this is not possible.

`?utm_medium=referral&utm_source=firefox.com&utm_campaign=unfck`

**Comment by pmac** [comment]
the way these work is that they add on to what is defined. So if someone came to `/unfck?utm_source=twitter` the end result would be `?utm_medium=referral&utm_source=firefox.com&utm_campaign=unfck&utm_source=twitter`, i.e. it would have two `utm_source` params. I have no idea how GA would treat that. Would it count it in both buckets, or just in whichever is last?

**Comment by pmac** [comment]
with these redirects though I assumed that they'd be mostly for people typing it in from seeing a print thing or hearing an add. If it's social or paid we can use a shorteners or link directly to the www.m.o page.

**Comment by pmac** [comment]
also, should it be `utm_source=firefox.com` or `utm_source=firefox-com`. The latter is what is used for all of the `redirect_source` values in the redirector.

**Comment by stephaniehobson** [comment]
Seems like duplicate UTMs will cause errors (invisible to the user but still a problem). 

Yes `utm_source=firefox.com`

I think it's possible we could have text ads that use `firefox.com/unfck` with UTM params. I'll double check with the team.

**Comment by stephaniehobson** [comment]
Looks like we can link directly to the landing page in all cases where we display the firefox.com/unfck url.

@alexgibson you may want to double-check that the tweet share button on the DE page is not linking to firefox.com with UTMs. For the EN page we are using http://mzl.la/unfck for the Twitter widget, which forwards to the landing page without going through firefox.com.

**Comment by stephaniehobson** [comment]
@pmac That means you can go ahead adding the UTM params to the redirects.

**Comment by hoosteeno** [comment]
I think these need to be true:

1. All downloads from this campaign get install attribution
a. If people click on a campaign link with utm params, we should pass those params through to attribution
b. If people get to the landing page somehow else and download, we should pass throrugh mozilla.org and page name into attribution

2. All visits from paid media are tracked in www GA
a. If people click on a campaign link with utm params, we should see those in www analytics

Can we confirm that the plan here achieves those things?

**Comment by alexgibson** [comment]
> b. If people get to the landing page somehow else and download, we should pass throrugh mozilla.org and page name into attribution

As discussed earlier in the week, stub attribution will pass along a combination of utm params, document.referrer and user agent. There’s no specific parameter for mozorg landing page URL. To add this is certainly do-able, but will likely take more coordination than we have time for before Oct 1. We could perhaps make a change to override document.referrer if it’s not set, but this would of course not capture the landing page URL if the value was set. So it would not answer the question entirely.

My advice here, would be that we always try and include utm parameters in these referral links / redirects.

**Comment by alexgibson** [comment]
The other option (on the bedrock side) is we consider this campaign landing page an experiment, and pass through an experiment name and variation for all page visits.

**Comment by alexgibson** [comment]
> Seems like duplicate UTMs will cause errors (invisible to the user but still a problem).

I think duplicate utm params would also result in some attributions not being recorded correctly (only the first match would be collected).

**Comment by pmac** [comment]
> > Seems like duplicate UTMs will cause errors (invisible to the user but still a problem).
> 
> I think duplicate utm params would also result in some attributions not being recorded correctly (only the first match would be collected).

It's in-spec for multiple query params with the same name to exist, so I don't think we can prevent it. These redirects aren't meant to be used as links in web ads really. They can be, but the real purpose IMO is for a memorable URL you can tell someone about in person or on the radio or podcast, or in an interview maybe. They're also for old URLs that we'd like to not be dead. 

If you'd like to make one that we know will be used in an ad people will click on, then we should leave it without params and let the UTM params come from the external link.

**Comment by alexgibson** [comment]
Ok, so I'm not really clear on what the consensus is here - we're not going to add any kind of default utm params to the vanity redirect? If we're adding them for podcast URLs like in https://github.com/mozmeao/www.firefox.com/pull/24, then maybe I don't understand why the rule is differnet here?

**Comment by alexgibson** [comment]
To be clear, what I'm not really understanding from the above is whether we'll be using ads with utms already in the URL. The comments from @stephaniehobson seem to suggest we won't, but I may be misinterpreting. On the other hand @pmac seems to be suggesting something differnent.

**Comment by hoosteeno** [comment]
In the absence of certainty about what URLs might come our way, is it possible we can build an nginx config that [accepts anything and behaves appropriately](https://en.wikipedia.org/wiki/Robustness_principle)? 

I am so far from being an nginx expert that my attempt here is probably best used as humorous fuel for your Friday afternoon, but maybe something like...

```
location ~* ^/unfu?ck/? {

  # https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#if
  if ($query_string ~* "utm_") {
  
    #http://nginx.org/en/docs/http/ngx_http_core_module.html#var_args
    rewrite (?i)^/unfu?ck/?$ https://www.mozilla.org/firefox/unfck/?redirect_source=firefox-com$args? permanent;
    
  }
  
  # https://forum.nginx.org/read.php?10,230949,238999#msg-238999
  if ($query_string ~* "(?!(utm_))" {
  
    rewrite (?i)^/unfu?ck/?$ https://www.mozilla.org/firefox/unfck/?redirect_source=firefox-com&utm_source=www.firefox.com&utm_campaign=unfck permanent;
    
  }
  
} 
```

**Comment by pmac** [comment]
That'd probably work. I guess I don't understand why we'd use firefox.com URLs in ads on which people will click, when we could just link directly to the real page.

**Comment by alexgibson** [comment]
> I guess I don't understand why we'd use firefox.com URLs in ads on which people will click, when we could just link directly to the real page.

I'm not clear on ads, but in social (i.e. twitter), we may use firefox.com/unfck because it's short and readable (plus mentions firefox in the url specifically)

**Comment by pmac** [comment]
and we'd put UTMs on it on social?

**Comment by alexgibson** [comment]
> and we'd put UTMs on it on social?

In the case of twitter no, becuase that creates a really long URL. It's really being used like a readable vanity redirect.

**Comment by pmac** [comment]
we could make a platform specific redirect for e.g. twitter so that the end result would have the UTMs.

**Comment by hoosteeno** [comment]
I think the real challenge is that we have limited control over what URLs people use. In the past we've made elaborate attempts to manage, but they all amount to a list of suggestions that the person building the in-channel treatment has to know about and understand. We could stand up at an all-team meeting and implore a certain behavior, and still a mistake could slip through, and if we don't anticipate that, we're leaving measurements on the floor.

**Comment by pmac** [comment]
I assume we'll be using mzl.la for a lot of social though too. I think it matters much more which account the is posting the link than the link itself.

**Comment by alexgibson** [comment]
If this is easier I'll see if we can get a mzl.la short link for the German page as well (which redirects directly to the landing page with UTMs). That's not really what they have asked for (they like the readable URL more), but if adding some default utms here is too complex then I'm sure they can live with it.

**Comment by alexgibson** [comment]
> I think it matters much more which account the is posting the link than the link itself.

The account could be anyone, as we encourage users to share a tweet via the landing page.

**Comment by pmac** [comment]
We can do anything I'm sure. Let's lay out exactly what we want and I'll make it happen. I'm confused at this point what that is though.

**Comment by alexgibson** [comment]
I thought what we wanted was:

- To have a set of default utm params in the redirect.
- To still honor existing utm params (and not overwrite them with defaults) if they already exist.

I'm still not clear on if the above is possible really

**Comment by alexgibson** [comment]
I'm going to talk to the EU team to see if they are ok using a short URL

**Comment by pmac** [comment]
Okay. PR filed. I believe that satisfies all of the needs. It will add default UTMs only if there are no UTMs on the incoming URI.

**Comment by alexgibson** [comment]
Great, thanks @pmac !

**Comment by pmac** [comment]
These changes are in prod. Looking good to me.

```
$ curl -I https://www.firefox.com/unfck\?utm_source=fish | grep location
location: https://www.mozilla.org/firefox/unfck/?redirect_source=firefox-com&utm_source=fish

$ curl -I https://www.firefox.com/unfck | grep location
location: https://www.mozilla.org/firefox/unfck/?redirect_source=firefox-com&utm_medium=referral&utm_source=firefox.com&utm_campaign=unfck
```

@stephaniehobson I have one last question though: for the unf?uck, love, and leibe URLs, do we want to add or change a param to indicate from which one of these the user came?

**Comment by stephaniehobson** [comment]
Talked with Edward about it an he doesn't think we need to be able to tell them apart.
