### ISSUE TITLE
September campaign podcast redirects

### ISSUE THREAD

**Issue by stephaniehobson** [mozmeao/www.firefox.com#21]
Ads being read on podcasts are going to use custom short URLs. The following need to redirect to the unfck landing page.

firefox.com/armchair
firefox.com/jvn
firefox.com/literally
firefox.com/pivot
firefox.com/podsave
firefox.com/smartless
firefox.com/thedaily
firefox.com/ezra
firefox.com/explained
firefox.com/wtf

For tracking purposes we will probably have to add UTMs to these based on what's decided in #19.

**Comment by pmac** [comment]
We'll probably need unique params for each of these right?

**Comment by stephaniehobson** [comment]
I'm thinking something like this:

?redirect_source=firefox.com&utm_source=**armchair**&utm_medium=podcast&utm_campaign=unfck
?redirect_source=firefox.com&utm_source=**jvn**&utm_medium=podcast&utm_campaign=unfck
?redirect_source=firefox.com&utm_source=**literally**&utm_medium=podcast&utm_campaign=unfck

Waiting for final word on the campaign.

**Comment by pmac** [comment]
Went ahead and merged the initial PR for these redirects. Reopening to track adding the UTM params.

**Comment by stephaniehobson** [comment]
Here's final for the UTM params:

?redirect_source=firefox.com?utm_medium=audio&utm_source=**armchair**&utm_campaign=unfck&utm_content=podcast 

You can swap out the utm_source to match the directory name for each redirect.
